version: '3'

services:
  voicemate-api:
    build: .
    depends_on:
      - voicemate-db
    container_name: voicemate-api
    environment:
      - GO_ENV=local
      - DBMS=postgres
      - DB_NAME=voicemate
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./voicemate_api:/go/src
    command: go run cmd/main.go
    tty: true
    ports:
      - "8000:8000"
  voicemate-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=voicemate
    container_name: voicemate-db
    volumes:
      - ./voicemate_database/definition:/docker-entrypoint-initdb.d # Init database and insert initial data.
      - ./voicemate_database/data:/var/lib/postgresql/data # Preserve data.
    tty: true
    ports:
      - 5433:5432
