---
swagger: "2.0"
info:
  description: "RESTful API for voicemate"
  version: "2021-09-24T14:52:39Z"
  title: "voicemate-api"
host: "localhost:8000"
schemes:
- "https"
paths:
  /:
    get:
      tags:
      - "test"
      responses:
        200:
          description: "Response on success"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Hello voicemate."
  /users/{id}:
    get:
      tags:
      - "users"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "number"
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/usersResponse"
    put:
      tags:
      - "users"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "number"
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/usersRequest" 
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/usersResponse"
    delete:
      tags:
      - "users"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "number"
      responses:
        200:
          description: "Response on success"
  /users:
    post:
      tags:
      - "users"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/usersRequest" 
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/usersResponse"
  /rooms/{id}:
    get:
      tags:
      - "rooms"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "number"
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/roomsResponse"
    put:
      tags:
      - "rooms"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "number"
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/roomsRequest" 
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/roomsResponse"
    delete:
      tags:
      - "rooms"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "number"
      responses:
        200:
          description: "Response on success"
  /rooms:
    get:
      tags:
      - "rooms"
      parameters:
      - name: "name"
        in: "query"
        required: false
        type: "string"
      - name: "age_lower"
        in: "query"
        required: false
        type: "string"
      - name: "age_upper"
        in: "query"
        required: false
        type: "string"
      - name: "gender"
        in: "query"
        required: false
        type: "string"
      - name: "member_limit"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/roomsResponse"
    post:
      tags:
      - "rooms"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/roomsRequest" 
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/roomsResponse"
  /tags/{id}:
    get:
      tags:
      - "tags"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "number"
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/tagsResponse"
    put:
      tags:
      - "tags"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "number"
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/tagsRequest" 
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/tagsResponse"
    delete:
      tags:
      - "tags"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "number"
      responses:
        200:
          description: "Response on success"
  /tags:
    post:
      tags:
      - "tags"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/tagsRequest" 
      responses:
        200:
          description: "Response on success"
          schema:
            $ref: "#/definitions/tagsResponse"
definitions:
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      name:
        type: "string"
        example: "野球"
  usersResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "uint64"
        example: 1
      name:
        type: "string"
        example: "test"
      age:
        type: "integer"
        format: "uint32"
        example: 20
      gender:
        type: "string"
        example: "male"
      email:
        type: "string"
        example: "test@example.com"
      password:
        type: "string"
        example: "test"
      roomID:
        type: "integer"
        format: "uint64"
        example: 1
      tags:
        type: "array"
        items:
          $ref: "#/definitions/Tag"
  roomsResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "uint64"
        example: 1
      name:
        type: "string"
        example: "test"
      ageLower:
        type: "integer"
        format: "uint32"
        example: 20
      ageUpper:
        type: "integer"
        format: "uint32"
        example: 50
      gender:
        type: "string"
        example: "male"
      memberLimit:
        type: "integer"
        format: "uint32"
        example: 5
      introduction:
        type: "string"
        example: "test"
      tags:
        type: "array"
        items:
          $ref: "#/definitions/Tag"
  tagsResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "uint64"
        example: 1
      name:
        type: "string"
        example: "野球"
  usersRequest:
    type: "object"
    properties:
      name:
        type: "string"
        example: "test"
      email:
        type: "string"
        example: "test@example.com"
      password:
        type: "string"
        example: "test"
  roomsRequest:
    type: "object"
    properties:
      name:
        type: "string"
        example: "test"
      ageLower:
        type: "integer"
        format: "uint32"
        example: 20
      ageUpper:
        type: "integer"
        format: "uint32"
        example: 50
      gender:
        type: "string"
        example: "male"
      memberLimit:
        type: "integer"
        format: "uint32"
        example: 5
      introduction:
        type: "string"
        example: "test"
  tagsRequest:
    type: "object"
    properties:
      name:
        type: "string"
        example: "サッカー"

